import type { Metadata } from "next";
import { Inter, Turret_Road } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        layout: { unsafe_disableDevelopmentModeWarnings: true },
      }}
    >
      <html lang="en" data-theme="dark">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
